disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - colon
  - comma

force_cast: warning
force_try:
  severity: warning

line_length: 125

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200
  
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
  
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
    
reporter: "xcode"
